CREATE TABLE IF NOT EXISTS students(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255),
  password VARCHAR(255),
  name     VARCHAR(255),
  school   VARCHAR(255),
  profile  TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
